// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-disorders.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/content/wiki-data.ts
var WIKI_DATA = [
  {
    id: "tlp",
    title: "Trastorno L\xEDmite de la Personalidad",
    short: "TLP",
    summary: "Inestabilidad intensa en emociones, autoimagen y v\xEDnculos, con un miedo profundo al abandono y una sensibilidad emocional que se vive a flor de piel.",
    clinicalLevel: "cl\xEDnico",
    cluster: "Cluster B",
    tags: ["personalidad", "regulaci\xF3n emocional", "v\xEDnculos", "DBT", "apego"],
    sections: [
      {
        id: "definicion",
        title: "Definici\xF3n cl\xEDnica",
        content: "Seg\xFAn el DSM-5-TR, el TLP es un patr\xF3n persistente de inestabilidad en las relaciones interpersonales, la autoimagen y la afectividad, junto con una marcada impulsividad. No es un defecto de car\xE1cter ni una elecci\xF3n: es un trastorno del sistema de regulaci\xF3n emocional. La persona siente las emociones con m\xE1s intensidad, las alcanza m\xE1s r\xE1pido y tarda m\xE1s en volver a la calma."
      },
      {
        id: "neurobiologia",
        title: "Base neurobiol\xF3gica",
        content: "Se observa una am\xEDgdala hiperreactiva (la alarma del miedo se dispara antes y m\xE1s fuerte) y una menor modulaci\xF3n desde la corteza prefrontal (el freno racional llega tarde). A esto se suma una sensibilidad documentada al rechazo. El resultado no es manipulaci\xF3n: es una respuesta biol\xF3gica desbordada que la propia persona muchas veces no entiende."
      },
      {
        id: "dinamica",
        title: "Din\xE1mica interpersonal",
        content: "Aparece el ciclo de idealizaci\xF3n y devaluaci\xF3n: hoy eres lo m\xE1s valioso del mundo, ma\xF1ana una amenaza. El esfuerzo por evitar el abandono puede volverse fren\xE9tico. La intensidad no significa falta de amor; muchas veces es exactamente lo contrario: amar con tanta fuerza que da v\xE9rtigo perderlo."
      },
      {
        id: "esperanza",
        title: "Pron\xF3stico y recuperaci\xF3n",
        content: "Es uno de los trastornos de personalidad con mejor pron\xF3stico. Con terapia (especialmente DBT, mentalizaci\xF3n y terapia de esquemas) muchas personas alcanzan remisi\xF3n sostenida. La regulaci\xF3n emocional se puede aprender. El TLP no es una sentencia."
      }
    ],
    criteria: [
      "Esfuerzos fren\xE9ticos para evitar un abandono real o imaginado.",
      "Relaciones intensas e inestables que alternan idealizaci\xF3n y devaluaci\xF3n.",
      "Alteraci\xF3n de la identidad: autoimagen inestable de forma marcada.",
      "Impulsividad en al menos dos \xE1reas potencialmente da\xF1inas (gasto, sexo, sustancias, conducci\xF3n, atracones).",
      "Conductas, gestos o amenazas de autolesi\xF3n recurrentes.",
      "Inestabilidad afectiva por reactividad del estado de \xE1nimo.",
      "Sentimientos cr\xF3nicos de vac\xEDo.",
      "Ira intensa e inapropiada o dificultad para controlarla.",
      "Ideaci\xF3n paranoide transitoria o s\xEDntomas disociativos graves bajo estr\xE9s."
    ],
    dynamics: [
      { context: "Pareja / persona favorita", desc: "La 'persona favorita' se vuelve ancla emocional: su atenci\xF3n regula y su silencio desestabiliza. Validar sin rescatar y sostener l\xEDmites firmes y amables es lo que crea seguridad real." },
      { context: "Amistad", desc: "V\xEDnculos profundos y leales, pero con miedo a ser reemplazado. Peque\xF1os cambios de tono se interpretan como rechazo. La constancia tranquila vale m\xE1s que las grandes promesas." },
      { context: "Familia", desc: "El hogar suele ser el escenario de las tormentas. Reducir la 'emoci\xF3n expresada' (cr\xEDtica y sobreimplicaci\xF3n) baja la frecuencia de crisis." },
      { context: "Colega / trabajo", desc: "Alta empat\xEDa y creatividad, pero la cr\xEDtica se vive como amenaza personal. El feedback concreto y privado funciona mejor que el p\xFAblico." }
    ],
    care: [
      "Validar la emoci\xF3n antes que discutir el hecho.",
      "L\xEDmites compasivos: 'No puedo ahora, s\xED ma\xF1ana' no es abandono.",
      "Constancia y previsibilidad bajan la alarma del sistema nervioso.",
      "Cuidar tambi\xE9n de ti: sostener a alguien no es vaciarte."
    ],
    hasAbrazo: true
  },
  {
    id: "tept-c",
    title: "Trauma complejo y TEPT",
    short: "TEPT / TEPT-C",
    summary: "Respuesta del sistema nervioso a un trauma \xFAnico o sostenido en el tiempo: revivir, evitar, hipervigilancia y una sensaci\xF3n constante de peligro que ya pas\xF3.",
    clinicalLevel: "cl\xEDnico",
    tags: ["trauma", "sistema nervioso", "memoria", "regulaci\xF3n", "disociaci\xF3n"],
    sections: [
      { id: "definicion", title: "Qu\xE9 es", content: "El TEPT surge tras la exposici\xF3n a un suceso traum\xE1tico. El TEPT complejo (TEPT-C) aparece tras trauma prolongado o repetido (a menudo en la infancia o en relaciones de abuso) y a\xF1ade dificultades de regulaci\xF3n emocional, autoconcepto negativo y problemas relacionales." },
      { id: "sintomas", title: "C\xF3mo se manifiesta", content: "Reexperimentaci\xF3n (flashbacks, pesadillas), evitaci\xF3n de lo que recuerda al trauma, hiperactivaci\xF3n (sobresaltos, insomnio, irritabilidad) y alteraciones del estado de \xE1nimo y la cognici\xF3n. En el TEPT-C, adem\xE1s, verg\xFCenza cr\xF3nica y sensaci\xF3n de estar 'roto'." },
      { id: "cuerpo", title: "El trauma vive en el cuerpo", content: "El sistema nervioso queda atascado en modo defensa. No es debilidad: es protecci\xF3n que se qued\xF3 encendida. La recuperaci\xF3n pasa por ense\xF1arle al cuerpo que el peligro termin\xF3." }
    ],
    dynamics: [
      { context: "Pareja", desc: "La intimidad puede activar alarmas antiguas. La seguridad se construye con previsibilidad, consentimiento y paciencia, no con presi\xF3n." },
      { context: "Amistad", desc: "Puede haber distancia protectora o, al rev\xE9s, apego intenso por miedo a la p\xE9rdida. Respetar el ritmo es clave." },
      { context: "Familia", desc: "Cuando el trauma viene del propio sistema familiar, poner distancia puede ser un acto de salud, no de traici\xF3n." }
    ],
    care: [
      "No fuerces el relato del trauma; acompa\xF1a el presente.",
      "Anclajes sensoriales (respiraci\xF3n, fr\xEDo, tacto) ayudan en los flashbacks.",
      "La terapia de trauma (EMDR, som\xE1tica, f\xE1sica) es de primera l\xEDnea."
    ]
  },
  {
    id: "bipolar",
    title: "Trastorno Bipolar",
    short: "TB",
    summary: "Alternancia entre fases de elevaci\xF3n del \xE1nimo (man\xEDa o hipoman\xEDa) y fases depresivas, en episodios que duran d\xEDas o semanas, no minutos.",
    clinicalLevel: "cl\xEDnico",
    tags: ["estado de \xE1nimo", "man\xEDa", "depresi\xF3n", "ciclos", "medicaci\xF3n"],
    sections: [
      { id: "definicion", title: "Qu\xE9 es", content: "Es un trastorno del estado de \xE1nimo con episodios diferenciados. En la man\xEDa hay euforia o irritabilidad, menos necesidad de dormir, impulsividad y grandiosidad; en la depresi\xF3n, todo lo contrario. Es biol\xF3gico y altamente tratable con medicaci\xF3n y psicoeducaci\xF3n." },
      { id: "diferencia", title: "No confundir con TLP", content: "La diferencia clave es el tiempo: en el TLP el \xE1nimo cambia en horas como reacci\xF3n a lo relacional; en el bipolar los episodios duran d\xEDas o semanas y no dependen tanto del contexto interpersonal." }
    ],
    dynamics: [
      { context: "Pareja", desc: "La estabilidad de rutinas (sue\xF1o, medicaci\xF3n) protege el v\xEDnculo. Aprender a reconocer se\xF1ales tempranas de un episodio es protecci\xF3n mutua." },
      { context: "Familia", desc: "La psicoeducaci\xF3n familiar reduce reca\xEDdas. Diferenciar 'la persona' de 'el episodio' evita resentimientos." }
    ],
    care: [
      "El sue\xF1o regular es un estabilizador del \xE1nimo.",
      "Acordar un plan de crisis en calma, para usarlo en episodio.",
      "No retirar la medicaci\xF3n sin acompa\xF1amiento profesional."
    ]
  },
  {
    id: "narcisista",
    title: "Trastorno Narcisista de la Personalidad",
    short: "TNP",
    summary: "Patr\xF3n de grandiosidad, necesidad de admiraci\xF3n y falta de empat\xEDa que, por debajo, suele esconder una autoestima extremadamente fr\xE1gil.",
    clinicalLevel: "cl\xEDnico",
    cluster: "Cluster B",
    tags: ["personalidad", "empat\xEDa", "autoestima", "v\xEDnculos", "din\xE1mica"],
    sections: [
      { id: "definicion", title: "Qu\xE9 es", content: "Detr\xE1s de la fachada de superioridad suele haber una herida narcisista: un yo que no soporta la verg\xFCenza. Existe el narcisismo grandioso (visible, dominante) y el vulnerable (encubierto, victimista). No todo el que es ego\xEDsta tiene TNP: es un patr\xF3n r\xEDgido y generalizado." },
      { id: "dinamica", title: "Din\xE1mica relacional", content: "El v\xEDnculo puede pasar por idealizaci\xF3n, devaluaci\xF3n y descarte. La empat\xEDa cognitiva (saber qu\xE9 sientes) puede estar presente sin empat\xEDa afectiva (importarle). Reconocerlo no es etiquetar para odiar, sino protegerte." }
    ],
    dynamics: [
      { context: "Pareja", desc: "Ciclo de love bombing, control sutil y devaluaci\xF3n. Recuperar criterio propio y red externa es esencial." },
      { context: "Colega", desc: "Tiende a apropiarse de logros y a desviar culpas. Documentar y poner l\xEDmites claros protege tu trabajo." },
      { context: "Familia", desc: "Roles asignados (el 'dorado', el 'chivo expiatorio') generan din\xE1micas da\xF1inas entre hermanos." }
    ],
    care: [
      "Conf\xEDa en lo que ves, no solo en lo que te dicen.",
      "Mant\xE9n una red de apoyo fuera del v\xEDnculo.",
      "L\xEDmites con consecuencias reales, no solo advertencias."
    ]
  },
  {
    id: "antisocial",
    title: "Trastorno Antisocial de la Personalidad",
    short: "TAP",
    summary: "Patr\xF3n de desprecio y violaci\xF3n de los derechos de los dem\xE1s, con dificultad para el remordimiento y tendencia a la manipulaci\xF3n.",
    clinicalLevel: "cl\xEDnico",
    cluster: "Cluster B",
    tags: ["personalidad", "empat\xEDa", "impulsividad", "riesgo"],
    sections: [
      { id: "definicion", title: "Qu\xE9 es", content: "Implica desprecio por las normas y los derechos ajenos, enga\xF1o, impulsividad y baja respuesta de culpa. La psicopat\xEDa es una variante con rasgos espec\xEDficos de frialdad emocional. Solo profesionales diagnostican: aqu\xED describimos para reconocer din\xE1micas, no para etiquetar." }
    ],
    dynamics: [
      { context: "Pareja", desc: "El encanto inicial puede ocultar control y explotaci\xF3n. La seguridad pasa por planes de salida y apoyo profesional." },
      { context: "Vecino / entorno", desc: "Transgresi\xF3n de l\xEDmites comunes sin culpa aparente. No personalices: protege tus espacios." }
    ],
    care: [
      "Tu seguridad f\xEDsica y emocional es prioridad uno.",
      "Evita el rol de 'salvador': no es tu responsabilidad cambiarlo.",
      "Busca apoyo especializado si hay abuso."
    ]
  },
  {
    id: "tdah",
    title: "TDAH",
    short: "TDAH",
    summary: "Patr\xF3n de inatenci\xF3n, impulsividad y/o hiperactividad de base neurobiol\xF3gica que afecta la regulaci\xF3n de la atenci\xF3n, el tiempo y las emociones.",
    clinicalLevel: "intermedio",
    tags: ["neurodivergencia", "atenci\xF3n", "impulsividad", "ejecutivo"],
    sections: [
      { id: "definicion", title: "Qu\xE9 es", content: "El TDAH no es falta de voluntad: es una diferencia en las funciones ejecutivas (planificar, iniciar, inhibir, recordar). La disregulaci\xF3n emocional y la 'disforia sensible al rechazo' son frecuentes y a veces se confunden con TLP." },
      { id: "diferencia", title: "No confundir con TLP", content: "Ambos comparten impulsividad y reactividad, pero en el TDAH no hay miedo central al abandono ni inestabilidad de identidad como eje. Pueden coexistir." }
    ],
    dynamics: [
      { context: "Pareja", desc: "Olvidos y desorganizaci\xF3n pueden leerse como desamor cuando no lo son. Sistemas externos (recordatorios, rutinas) ayudan m\xE1s que los reproches." },
      { context: "Colega", desc: "Creatividad y foco intenso en lo que motiva; dificultad con lo tedioso. Acuerdos claros y plazos visibles funcionan." }
    ],
    care: [
      "Estructura externa > fuerza de voluntad.",
      "Separar la conducta del afecto: 'olvid\xF3' no es 'no le importas'.",
      "Tratamiento combinado (psicoeducaci\xF3n + a veces medicaci\xF3n) es eficaz."
    ]
  },
  {
    id: "depresion",
    title: "Depresi\xF3n",
    short: "TDM",
    summary: "M\xE1s que tristeza: una bajada sostenida del \xE1nimo, la energ\xEDa y la capacidad de disfrutar que altera el sue\xF1o, el apetito y el pensamiento.",
    clinicalLevel: "intermedio",
    tags: ["estado de \xE1nimo", "energ\xEDa", "anhedonia", "tratamiento"],
    sections: [
      { id: "definicion", title: "Qu\xE9 es", content: "La depresi\xF3n mayor implica estado de \xE1nimo bajo o p\xE9rdida de inter\xE9s casi todos los d\xEDas durante al menos dos semanas, con cambios en sue\xF1o, apetito, concentraci\xF3n y sensaci\xF3n de inutilidad. No se 'sale poniendo de tu parte': es un cuadro tratable." }
    ],
    dynamics: [
      { context: "Pareja", desc: "El retraimiento no es rechazo. Acompa\xF1ar sin presionar y cuidar el propio desgaste sostiene el v\xEDnculo." },
      { context: "Amistad", desc: "La presencia constante y sin exigencias vale m\xE1s que los consejos. Invitar sin condicionar la respuesta." }
    ],
    care: [
      "Peque\xF1os pasos diarios antes que grandes metas.",
      "Pedir ayuda profesional no es rendirse, es estrategia.",
      "Vigilar se\xF1ales de riesgo y conocer l\xEDneas de crisis."
    ]
  },
  {
    id: "ansiedad",
    title: "Trastornos de Ansiedad",
    short: "TAG / fobias",
    summary: "Sistema de alarma que se activa sin peligro real: preocupaci\xF3n excesiva, anticipaci\xF3n catastr\xF3fica y s\xEDntomas f\xEDsicos de miedo.",
    clinicalLevel: "b\xE1sico",
    tags: ["ansiedad", "miedo", "cuerpo", "evitaci\xF3n"],
    sections: [
      { id: "definicion", title: "Qu\xE9 es", content: "Incluye el trastorno de ansiedad generalizada, las fobias, el p\xE1nico y la ansiedad social. El cuerpo reacciona como ante una amenaza (taquicardia, tensi\xF3n, mareo) aunque la mente sepa que no la hay. La evitaci\xF3n alivia a corto plazo pero alimenta el miedo." }
    ],
    dynamics: [
      { context: "Pareja", desc: "Pedir reaseguro constante puede agotar. Acompa\xF1ar sin reforzar la evitaci\xF3n es el equilibrio sano." },
      { context: "Colega", desc: "El perfeccionismo ansioso rinde pero desgasta. Normalizar el error reduce la presi\xF3n." }
    ],
    care: [
      "Respiraci\xF3n lenta y exposici\xF3n gradual, no evitaci\xF3n.",
      "Reducir cafe\xEDna y mejorar el sue\xF1o bajan la activaci\xF3n.",
      "La TCC tiene gran evidencia para la ansiedad."
    ]
  },
  {
    id: "toc",
    title: "Trastorno Obsesivo-Compulsivo",
    short: "TOC",
    summary: "Obsesiones (pensamientos intrusivos que generan angustia) y compulsiones (rituales para aliviarla) que consumen tiempo y libertad.",
    clinicalLevel: "intermedio",
    tags: ["obsesiones", "compulsiones", "ansiedad", "rituales"],
    sections: [
      { id: "definicion", title: "Qu\xE9 es", content: "No es ser ordenado o meticuloso. Es un ciclo agotador: un pensamiento intrusivo (contaminaci\xF3n, da\xF1o, duda) dispara angustia, y un ritual (lavado, comprobaci\xF3n, repetici\xF3n mental) la calma un momento... y la refuerza para la pr\xF3xima vez." }
    ],
    dynamics: [
      { context: "Pareja", desc: "La familia puede quedar 'acomodando' los rituales sin querer. Dejar de acomodarlos, con apoyo terap\xE9utico, ayuda a romper el ciclo." }
    ],
    care: [
      "No discutas con la obsesi\xF3n: trabaja la respuesta al malestar.",
      "La EPR (exposici\xF3n con prevenci\xF3n de respuesta) es el tratamiento de elecci\xF3n.",
      "Evita dar reaseguros infinitos."
    ]
  },
  {
    id: "evitativo",
    title: "Trastorno Evitativo de la Personalidad",
    short: "TEvP",
    summary: "Inhibici\xF3n social, sentimientos de inadecuaci\xF3n e hipersensibilidad a la evaluaci\xF3n negativa que llevan a evitar el contacto pese al deseo de v\xEDnculo.",
    clinicalLevel: "intermedio",
    cluster: "Cluster C",
    tags: ["personalidad", "verg\xFCenza", "apego", "v\xEDnculos"],
    sections: [
      { id: "definicion", title: "Qu\xE9 es", content: "Quieren cercan\xEDa pero la evitan por miedo al rechazo y a la humillaci\xF3n. No es desinter\xE9s: es protecci\xF3n. Se diferencia de la fobia social por ser un patr\xF3n m\xE1s profundo y estable de autoimagen de inadecuaci\xF3n." }
    ],
    dynamics: [
      { context: "Pareja", desc: "Necesitan garant\xEDas de aceptaci\xF3n incondicional antes de abrirse. La presi\xF3n los aleja; la paciencia los acerca." }
    ],
    care: [
      "Avances peque\xF1os y seguros en exposici\xF3n social.",
      "Reforzar lo que s\xED hacen, sin sobreproteger."
    ]
  },
  {
    id: "dependiente",
    title: "Trastorno de la Personalidad por Dependencia",
    short: "TPD",
    summary: "Necesidad excesiva de ser cuidado que lleva a sumisi\xF3n, miedo a la separaci\xF3n y dificultad para tomar decisiones por cuenta propia.",
    clinicalLevel: "intermedio",
    cluster: "Cluster C",
    tags: ["personalidad", "apego", "autonom\xEDa", "v\xEDnculos"],
    sections: [
      { id: "definicion", title: "Qu\xE9 es", content: "El temor a quedarse solo lleva a ceder, complacer y delegar decisiones vitales en otros. Puede confundirse con amor entregado, pero el eje es el miedo, no el cuidado libre." }
    ],
    dynamics: [
      { context: "Pareja", desc: "Riesgo de relaciones desequilibradas o de quedar atrapado en v\xEDnculos da\xF1inos por miedo a la soledad. Recuperar autonom\xEDa gradual es el camino." }
    ],
    care: [
      "Fomentar peque\xF1as decisiones propias cada d\xEDa.",
      "No castigar la dependencia: acompa\xF1ar la autonom\xEDa."
    ]
  },
  {
    id: "espectro-autista",
    title: "Espectro Autista (TEA)",
    short: "TEA",
    summary: "Una forma distinta de procesar lo social y lo sensorial. No es un trastorno relacional por da\xF1o: es neurodivergencia, con necesidades y fortalezas propias.",
    clinicalLevel: "intermedio",
    tags: ["neurodivergencia", "sensorial", "comunicaci\xF3n", "v\xEDnculos"],
    sections: [
      { id: "definicion", title: "Qu\xE9 es", content: "Implica diferencias en comunicaci\xF3n social, intereses intensos, necesidad de previsibilidad y sensibilidad sensorial. Lo incluimos para deshacer un mito frecuente: el autismo no es manipulaci\xF3n ni falta de empat\xEDa, es otra forma de estar en el mundo." }
    ],
    dynamics: [
      { context: "Pareja", desc: "La literalidad y la honestidad pueden malinterpretarse como frialdad. La comunicaci\xF3n expl\xEDcita y clara evita malentendidos." },
      { context: "Colega", desc: "Foco profundo y rigor; necesita instrucciones claras y entornos sensorialmente amables." }
    ],
    care: [
      "Comunicaci\xF3n directa, concreta y sin dobles sentidos.",
      "Respetar necesidades sensoriales y de previsibilidad.",
      "No patologizar lo que solo es diferencia."
    ]
  }
];
var DUDAS = [
  {
    id: "es-normal",
    category: "\xBFEs normal que\u2026?",
    icon: "\u{1F4AD}",
    intro: "Las preguntas que mucha gente piensa en voz baja y casi nadie se atreve a decir.",
    questions: [
      { q: "\xBFEs normal sentir que camino sobre c\xE1scaras de huevo?", a: "Sentir que mides cada palabra para no provocar una reacci\xF3n es una se\xF1al de que la relaci\xF3n te tiene en alerta constante. Es muy com\xFAn, y no es lo que deber\xEDa sentirse un v\xEDnculo seguro." },
      { q: "\xBFEs normal que un d\xEDa sea idealizado y al siguiente, despreciado?", a: "El cambio brusco entre 'eres todo' y 'no vales nada' (idealizaci\xF3n-devaluaci\xF3n) es agotador y desorientador. Ocurre en algunas din\xE1micas, pero no es la base de un amor estable." },
      { q: "\xBFEs normal dudar de mi propia memoria de lo que pas\xF3?", a: "Si sales de las conversaciones confundido sobre qu\xE9 ocurri\xF3 realmente, podr\xEDas estar viviendo gaslighting. Apuntar los hechos cuando est\xE1s en calma ayuda a recuperar tu criterio." },
      { q: "\xBFEs normal querer a alguien y a la vez sentir que me vac\xEDa?", a: "El amor y el agotamiento pueden coexistir. Que quieras a alguien no significa que la din\xE1mica sea sana. Ambas cosas pueden ser verdad al mismo tiempo." },
      { q: "\xBFEs normal sentirme responsable de su estabilidad emocional?", a: "Sentir que eres el termostato emocional de otra persona es una carga insostenible. Acompa\xF1ar no es ser responsable de regular a alguien las 24 horas." }
    ]
  },
  {
    id: "limites",
    category: "L\xEDmites y culpa",
    icon: "\u{1F6E1}\uFE0F",
    intro: "Poner l\xEDmites no es abandonar. Es la condici\xF3n para que un v\xEDnculo sea sostenible.",
    questions: [
      { q: "Si pongo un l\xEDmite, \xBFlo estoy abandonando?", a: "No. Un l\xEDmite dice 'esto es lo que puedo dar para seguir aqu\xED'. Abandonar es irse; poner l\xEDmites es, muchas veces, lo que permite quedarse sin destruirse." },
      { q: "\xBFPor qu\xE9 me siento culpable al cuidar de m\xED?", a: "Si creciste cuidando a otros, tu sistema interpreta el autocuidado como ego\xEDsmo. No lo es. Cuidarte es lo que te permite seguir cuidando sin vaciarte." },
      { q: "\xBFEst\xE1 mal necesitar tiempo a solas?", a: "Necesitar espacio es humano y sano. Un v\xEDnculo seguro tolera la distancia sin vivirla como amenaza." },
      { q: "\xBFC\xF3mo pongo un l\xEDmite sin herir a alguien fr\xE1gil?", a: "Valida primero, luego limita: 'S\xE9 que esto te duele y me importas; aun as\xED, no puedo seguir esta conversaci\xF3n ahora'. Firmeza y ternura a la vez." }
    ]
  },
  {
    id: "soy-yo",
    category: "\xBFY si soy yo?",
    icon: "\u{1FA9E}",
    intro: "Mirarse con honestidad no es culparse. Es el primer paso para cambiar.",
    questions: [
      { q: "\xBFY si la persona con el problema soy yo?", a: "Hacerse esta pregunta ya habla de capacidad de autoobservaci\xF3n, algo que rara vez aparece en quien da\xF1a sin registro. Buscar evaluaci\xF3n profesional es un acto de responsabilidad, no de culpa." },
      { q: "\xBFTener rasgos de un trastorno significa tenerlo?", a: "No. Todas las personas tenemos algo de cada rasgo en distintos niveles. Un trastorno es un patr\xF3n r\xEDgido, persistente y que genera sufrimiento o disfunci\xF3n. El nivel lo determina un profesional." },
      { q: "\xBFPuedo cambiar si reconozco mis patrones?", a: "S\xED. El reconocimiento es la puerta. Con acompa\xF1amiento, los patrones aprendidos se pueden reescribir. La biolog\xEDa predispone, no condena." }
    ]
  },
  {
    id: "diferencias",
    category: "Diferencias entre trastornos",
    icon: "\u{1F9ED}",
    intro: "Personalidad no es lo mismo que trastorno, y cada cuadro tiene su propia l\xF3gica.",
    questions: [
      { q: "\xBFEn qu\xE9 se diferencia el TLP del trastorno bipolar?", a: "En el tiempo y el disparador. En el TLP el \xE1nimo cambia en horas, casi siempre por algo relacional. En el bipolar los episodios duran d\xEDas o semanas y son m\xE1s independientes del contexto." },
      { q: "\xBFPersonalidad y trastorno de personalidad son lo mismo?", a: "No. La personalidad es tu forma estable de ser. Se vuelve 'trastorno' solo cuando un patr\xF3n es r\xEDgido, generalizado y causa sufrimiento o problemas serios de funcionamiento." },
      { q: "\xBFEl TDAH se confunde con el TLP?", a: "Comparten impulsividad y reactividad emocional, pero el TDAH no tiene como eje el miedo al abandono ni la inestabilidad de identidad. A veces coexisten." },
      { q: "\xBFTodo el que es ego\xEDsta es narcisista?", a: "No. El narcisismo como trastorno es un patr\xF3n r\xEDgido y generalizado de grandiosidad y falta de empat\xEDa, no un mal d\xEDa o un rasgo aislado." }
    ]
  },
  {
    id: "manipulacion",
    category: "Manipulaci\xF3n y din\xE1micas da\xF1inas",
    icon: "\u26A0\uFE0F",
    intro: "Reconocer una t\xE1ctica no es etiquetar para odiar: es recuperar tu criterio.",
    questions: [
      { q: "\xBFQu\xE9 es el love bombing?", a: "Una avalancha de atenci\xF3n, regalos y promesas al inicio que crea dependencia r\xE1pida. Lo sano se construye con tiempo; lo que va demasiado r\xE1pido conviene observarlo con calma." },
      { q: "\xBFQu\xE9 es el hoovering?", a: "El intento de 'reabsorberte' justo cuando intentas alejarte: mensajes de cambio, promesas, crisis repentinas. Anticiparlo te ayuda a no recaer en autom\xE1tico." },
      { q: "\xBFQu\xE9 es DARVO?", a: "Negar, atacar e invertir v\xEDctima y agresor. El que da\xF1a se presenta como la verdadera v\xEDctima. Reconocer el patr\xF3n evita que cargues una culpa que no es tuya." },
      { q: "\xBFLa intensidad es lo mismo que el amor?", a: "No necesariamente. La intensidad activa el cuerpo, pero la seguridad lo calma. Un v\xEDnculo sano puede ser intenso y, a la vez, tranquilo." }
    ]
  },
  {
    id: "ayuda",
    category: "Pedir ayuda y soltar",
    icon: "\u{1F331}",
    intro: "Cu\xE1ndo acompa\xF1ar, cu\xE1ndo poner distancia y c\xF3mo cuidarte en el proceso.",
    questions: [
      { q: "\xBFCu\xE1ndo acompa\xF1ar y cu\xE1ndo alejarme?", a: "Acompa\xF1a cuando hay reconocimiento, cuidado mutuo y cambios reales. Plant\xE9ate distancia cuando la relaci\xF3n te anula, te a\xEDsla o te hace sentir inseguro de forma sostenida." },
      { q: "\xBFSoltar es una traici\xF3n?", a: "No. Si una relaci\xF3n te vac\xEDa, poner distancia es un acto de cuidado, no de abandono. Puedes querer a alguien y aun as\xED no poder quedarte." },
      { q: "\xBFC\xF3mo s\xE9 si necesito ayuda profesional?", a: "Si el malestar interfiere con tu vida diaria, tus relaciones o tu salud, es momento de buscar apoyo. Pedir ayuda es estrategia, no debilidad." },
      { q: "\xBFY si la otra persona no quiere ayuda?", a: "No puedes obligar a nadie a tratarse. S\xED puedes decidir c\xF3mo te cuidas t\xFA, qu\xE9 l\xEDmites pones y qu\xE9 apoyo buscas para ti." }
    ]
  }
];
var CLINICAL_LEVELS = {
  b\u00E1sico: "Lectura accesible",
  intermedio: "Profundidad media",
  cl\u00EDnico: "Detalle cl\xEDnico"
};
var WIKI_DISCLAIMER = "Esta enciclopedia es educativa y no sustituye una evaluaci\xF3n cl\xEDnica. Nadie debe diagnosticarse a s\xED mismo ni a otros: solo profesionales con experiencia diagnostican. Si est\xE1s en crisis, contacta con l\xEDneas de apoyo o servicios de emergencia.";

// src/lib/mcp/tools/list-disorders.ts
var list_disorders_default = defineTool({
  name: "list_disorders",
  title: "List disorders",
  description: "List every mental-health disorder covered by the encyclopedia, with its id, name, short name, clinical level and one-line summary. Use the id with get_disorder for full detail.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = WIKI_DATA.map((d) => ({
      id: d.id,
      title: d.title,
      short: d.short,
      clinicalLevel: d.clinicalLevel,
      level: CLINICAL_LEVELS[d.clinicalLevel],
      cluster: d.cluster,
      tags: d.tags,
      summary: d.summary,
      hasAbrazo: Boolean(d.hasAbrazo)
    }));
    const text = items.map((d) => `\u2022 ${d.title} (${d.short}) \u2014 id: ${d.id} \u2014 nivel: ${d.level}
  ${d.summary}`).join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { count: items.length, disorders: items }
    };
  }
});

// src/lib/mcp/tools/get-disorder.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var get_disorder_default = defineTool2({
  name: "get_disorder",
  title: "Get disorder detail",
  description: "Get the full encyclopedia entry for one disorder by its id (from list_disorders): clinical definition, neurobiology, DSM-5 criteria, relationship dynamics across contexts, and self-care guidance.",
  inputSchema: {
    id: z.string().min(1).describe("Disorder id, e.g. 'tlp', 'tept-c', 'bipolar' (from list_disorders).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const d = WIKI_DATA.find((x) => x.id === id.trim().toLowerCase());
    if (!d) {
      const ids = WIKI_DATA.map((x) => x.id).join(", ");
      return {
        content: [{ type: "text", text: `No existe un trastorno con id "${id}". Ids disponibles: ${ids}` }],
        isError: true
      };
    }
    const parts = [];
    parts.push(`# ${d.title} (${d.short})`);
    parts.push(`Nivel cl\xEDnico: ${CLINICAL_LEVELS[d.clinicalLevel]}${d.cluster ? ` \xB7 ${d.cluster}` : ""}`);
    parts.push(`
${d.summary}`);
    for (const s of d.sections) parts.push(`
## ${s.title}
${s.content}`);
    if (d.criteria?.length) parts.push(`
## Criterios
${d.criteria.map((c) => `- ${c}`).join("\n")}`);
    if (d.dynamics?.length)
      parts.push(`
## Din\xE1mica relacional
${d.dynamics.map((x) => `- ${x.context}: ${x.desc}`).join("\n")}`);
    if (d.care?.length) parts.push(`
## Autocuidado
${d.care.map((c) => `- ${c}`).join("\n")}`);
    parts.push(`
---
${WIKI_DISCLAIMER}`);
    return {
      content: [{ type: "text", text: parts.join("\n") }],
      structuredContent: { disorder: d, disclaimer: WIKI_DISCLAIMER }
    };
  }
});

// src/lib/mcp/tools/search-encyclopedia.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var search_encyclopedia_default = defineTool3({
  name: "search_encyclopedia",
  title: "Search encyclopedia",
  description: "Full-text search across the encyclopedia: disorder names, summaries, sections, criteria, relationship dynamics, and the FAQ. Returns the best-matching disorders and questions for a query.",
  inputSchema: {
    query: z2.string().min(2).describe("Search terms, e.g. 'miedo al abandono', 'l\xEDmites', 'gaslighting'."),
    limit: z2.number().int().min(1).max(25).default(8).describe("Max results to return (default 8).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, limit }) => {
    const q = query.trim().toLowerCase();
    const terms = q.split(/\s+/).filter(Boolean);
    const score = (haystack) => {
      const h = haystack.toLowerCase();
      return terms.reduce((n, t) => h.includes(t) ? n + 1 : n, 0);
    };
    const disorderHits = WIKI_DATA.map((d) => {
      const blob = [d.title, d.short, d.summary, ...d.tags, ...d.sections.map((s) => `${s.title} ${s.content}`), ...d.criteria ?? [], ...d.dynamics.map((x) => `${x.context} ${x.desc}`)].join(" ");
      return { d, s: score(blob) };
    }).filter((x) => x.s > 0).sort((a, b) => b.s - a.s).map((x) => ({ type: "disorder", id: x.d.id, title: x.d.title, short: x.d.short, summary: x.d.summary }));
    const faqHits = DUDAS.flatMap(
      (cat) => cat.questions.map((item) => ({ cat, item, s: score(`${item.q} ${item.a}`) }))
    ).filter((x) => x.s > 0).sort((a, b) => b.s - a.s).map((x) => ({ type: "faq", category: x.cat.category, question: x.item.q, answer: x.item.a }));
    const results = [...disorderHits, ...faqHits].slice(0, limit);
    if (results.length === 0)
      return { content: [{ type: "text", text: `Sin resultados para "${query}".` }], structuredContent: { results: [] } };
    const text = results.map(
      (r) => r.type === "disorder" ? `\u{1F4D8} ${r.title} (${r.short}) \u2014 id: ${r.id}
   ${r.summary}` : `\u2753 [${r.category}] ${r.question}
   ${r.answer}`
    ).join("\n\n");
    return { content: [{ type: "text", text }], structuredContent: { count: results.length, results } };
  }
});

// src/lib/mcp/tools/list-faqs.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_faqs_default = defineTool4({
  name: "list_faqs",
  title: "List FAQs",
  description: "List the encyclopedia's frequently-asked questions and answers about relationships and mental health, grouped by category (boundaries, is-it-me, manipulation, asking for help, etc.). Optionally filter by a category id.",
  inputSchema: {
    category: z3.string().optional().describe("Optional category id to filter by, e.g. 'limites', 'manipulacion' (omit for all).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const cats = category ? DUDAS.filter((c) => c.id === category.trim().toLowerCase()) : DUDAS;
    if (cats.length === 0) {
      const ids = DUDAS.map((c) => `${c.id} (${c.category})`).join(", ");
      return {
        content: [{ type: "text", text: `No hay categor\xEDa "${category}". Disponibles: ${ids}` }],
        isError: true
      };
    }
    const text = cats.map((c) => `${c.icon} ${c.category} \u2014 id: ${c.id}
${c.questions.map((qa) => `  \u2022 ${qa.q}
    ${qa.a}`).join("\n")}`).join("\n\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: {
        categories: cats.map((c) => ({ id: c.id, category: c.category, questions: c.questions }))
      }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "abrazo-encyclopedia-mcp",
  title: "ABRAZO \xB7 Encyclopedia of Dynamics",
  version: "0.1.0",
  instructions: "Public, Spanish-first reference on mental-health disorders and their relationship dynamics (couples, family, friends, colleagues). Use `search_encyclopedia` to find relevant content, `list_disorders` to browse the catalog, `get_disorder` for a full clinical entry by id, and `list_faqs` for common questions about boundaries, manipulation and asking for help. This is educational content, not a diagnosis or a substitute for professional care.",
  tools: [search_encyclopedia_default, list_disorders_default, get_disorder_default, list_faqs_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
